# Hydra defaults and settings. Ignore these (don't change)
defaults:
  - paths: default
  - morphology: morphology
  - _self_

hydra:
  run:
    dir: ${paths.logdir}/${job.job_now}
  output_subdir: ${hydra.run.dir}/hydra

pipeline:
  # - find_unprocessed_batches
  # - download_batch
  # - detect_weeds
  - unet_segment_weeds

download_batch:
  use_multithreading: True
  download_limit: 1

segment_weeds:
  multiprocess: False
  
general:
  task: # Leave empty as placeholder

pipeline_keys: ${paths.workdir}/keys/authorized_keys.yaml

job:
  job_now_date: &nowdir ${now:%Y-%m-%d}
  job_now_time: ${now:%H_%M_%S}
  job_now: ${job.job_now_date}/${job.job_now_time} 
  jobdir: ${paths.datadir}/${job.job_now}

morphology_species: ${general.workdir}/conf/morphology/morphology.yaml
