# Hydra defaults and settings. Ignore these (don't change)
defaults:
  - paths: default
  - morphology: morphology
  - _self_

hydra:
  run:
    dir: ${paths.logdir}/${job.job_now}
  output_subdir: ${hydra.run.dir}/hydra

pipeline:
  # - find_unprocessed_batches
  # - download_batch
  # - detect_weeds
  - unet_segment_weeds

download_batch:
  use_multithreading: True
  download_limit: 20

segment_weeds:
  multiprocess: False
  
general:
  task: # Leave empty as placeholder

pipeline_keys: ${paths.workdir}/keys/authorized_keys.yaml

job:
  job_now_date: &nowdir ${now:%Y-%m-%d}
  job_now_time: ${now:%H_%M_%S}
  job_now: ${job.job_now_date}/${job.job_now_time} 
  jobdir: ${paths.datadir}/${job.job_now}

#delete this:
morphology_species: ${general.workdir}/conf/morphology/morphology.yaml

inference_for_pipeline:
  save_mask: False # If true, the segmented image will be saved
  overlay_comparison: False # If true, the original image and the segmented image will be overlayed
  side_by_side_comparison: True # If true, the original image and the segmented image will be displayed side by side but greatly increases the time to process
