# Hydra defaults and settings. Ignore these (don't change)
defaults:
  - override hydra/job_logging: custom # custom logging 
  - _self_

hydra:
  run:
    dir: ${logs.logdir}/${job.job_now}
  output_subdir: ${hydra.run.dir}/hydra

pipeline:
  # - scripttemplate
  - detect_segment_weeds
  

general:
  task: # Leave empty as placeholder
  workdir: ${hydra:runtime.cwd}  # where the code is executed

pipeline_keys: ${general.workdir}/keys/authorized_keys.yaml

data:
  datadir: ${general.workdir}/data
  temp_image_dir: ${data.datadir}/images_testing
  temp_output_dir: ${data.datadir}/images_testing/vit_l_output

  path_yolo_model: ${data.datadir}/models/weed_detection/weights/best.pt
  sam_checkpoint: ${data.datadir}/models/SAM parmameters/SAM checkpoint/sam_vit_l_0b3195.pth
  sam_model_type: "vit_l"

logs:
  logdir: ${general.workdir}/logging

job:
  job_now_date: &nowdir ${now:%Y-%m-%d}
  job_now_time: ${now:%H_%M_%S}
  job_now: ${job.job_now_date}/${job.job_now_time} 
  jobdir: ${data.datadir}/${job.job_now}