category_field_map:
  class_id: class_id
  USDA_symbol: usda_symbol
  EPPO: eppo
  group: taxonomic_group
  class: taxonomic_class
  subclass: taxonomic_subclass
  order: taxonomic_order
  family: taxonomic_family
  genus: taxonomic_genus
  species: taxonomic_species_name
  common_name: common_name
  authority: taxonomic_authority
  growth_habit: growth_habit
  duration: duration
  multi_species_USDA_symbol: multi_species_USDA_symbol
  link: link
  note: category_note
  rgb: rgb
  alias: alias

table_to_db_map:
  BatchID: batch_id
  Name: image_id
  CameraInfo_DateTime: camera_datetime
  CloudCover: cloud_cover
  CottonVariety: cotton_variety
  CoverCropFamily: cover_crop_family
  CropOrFallow: crop_or_fallow
  CropTypeSecondary: crop_type_secondary
  FlowerFruitOrSeeds: flower_fruit_or_seeds
  GroundCover: ground_cover
  GroundResidue: ground_residue
  GrowthStage: growth_stage
  HasMatchingJpgAndRaw: has_matching_jpg_and_raw
  Height: height
  ImageIndex: image_index
  ImageIDUnixDT: image_id_unixdt
  ImageURL: image_url
  MasterRefID: wirmaster_ref_id
  PlantType: plant_type
  SizeClass: size_class
  SizeMiB: size_mib
  Species: app_species
  SubBatchIndex: sub_batch_index
  Stem: stem # Unique identifier for the image
  Extension: extension
  UploadDateTimeUTC: upload_datetime_utc
  UsState: us_state
  Wircovercropsmeta_rowkey: wircovercropsmeta_rowkey
  Wircropsmeta_rowkey: wircropsmeta_rowkey
  Wirimagerefs_rowkey: wirimagerefs_rowkey
  Wirmastermeta_rowkey: wirmastermeta_rowkey
  Wirweedsmeta_rowkey: wirweedsmeta_rowkey

db_columns:
  - id
  - db_insert_datetime
  - app_species
  - batch_id
  - extension
  - extension_lower
  - stem
  - camera_datetime
  - cloud_cover
  - cotton_variety
  - cover_crop_family
  - crop_or_fallow
  - crop_type_secondary
  - flower_fruit_or_seeds
  - ground_cover
  - ground_residue
  - growth_stage
  - has_matching_jpg_and_raw
  - height
  - image_id
  - image_id_unixdt
  - image_index
  - image_url
  - is_preprocessed
  - plant_type
  - size_class
  - size_mib
  - sub_batch_index
  - upload_datetime_utc
  - us_state
  - wircovercropsmeta_rowkey
  - wircropsmeta_rowkey
  - wirimagerefs_rowkey
  - wirmaster_ref_id
  - wirmastermeta_rowkey
  - wirweedsmeta_rowkey
  - note
  - bbox_xywh
  - det_pred_conf
  - has_mat_pred
  - has_mat_pred_conf
  - class_id
  - usda_symbol
  - eppo
  - taxonomic_group
  - taxonomic_class
  - taxonomic_subclass
  - taxonomic_order
  - taxonomic_family
  - taxonomic_genus
  - taxonomic_species_name
  - taxonomic_authority
  - common_name
  - growth_habit
  - duration
  - multi_species_USDA_symbol
  - link
  - category_note
  - rgb
  - alias
  - exif_meta
  - cutout_name
  - raw_image_path
  - developed_image_path
  - initial_mask_path
  - refined_mask_path
  - relabeled_mask_path
  - refined_params
  - initial_mask_issue_tag
  - final_mask_issue_tag
  - final_mask_path
  - mask_status
  - mask_reviewer
  - mask_review_datetime

exif_meta_fields:
 - Image Make
 - Image Model
 - Image Software
 - EXIF ExposureTime
 - EXIF FNumber
 - EXIF ISOSpeedRatings
 - EXIF Flash
 - EXIF FocalLength
 - EXIF LensModel